require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ofuros", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Ofuro. As you add validations to Ofuro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Ofuro.create! valid_attributes
      get ofuros_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ofuro = Ofuro.create! valid_attributes
      get ofuro_url(ofuro)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ofuro_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      ofuro = Ofuro.create! valid_attributes
      get edit_ofuro_url(ofuro)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a " do
        expect {
          post ofuros_url, params: { ofuro: valid_attributes }
        }.to change(Ofuro, :count).by(1)
      end

      it "redirects to the created ofuro" do
        post ofuros_url, params: { ofuro: valid_attributes }
        expect(response).to redirect_to(ofuro_url(Ofuro.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ofuro" do
        expect {
          post ofuros_url, params: { ofuro: invalid_attributes }
        }.to change(Ofuro, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ofuros_url, params: { ofuro: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ofuro" do
        ofuro = Ofuro.create! valid_attributes
        patch ofuro_url(ofuro), params: { ofuro: new_attributes }
        ofuro.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ofuro" do
        ofuro = Ofuro.create! valid_attributes
        patch ofuro_url(ofuro), params: { ofuro: new_attributes }
        ofuro.reload
        expect(response).to redirect_to(ofuro_url(ofuro))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ofuro = Ofuro.create! valid_attributes
        patch ofuro_url(ofuro), params: { ofuro: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ofuro" do
      ofuro = Ofuro.create! valid_attributes
      expect {
        delete ofuro_url(ofuro)
      }.to change(Ofuro, :count).by(-1)
    end

    it "redirects to the ofuros list" do
      ofuro = Ofuro.create! valid_attributes
      delete ofuro_url(ofuro)
      expect(response).to redirect_to(ofuros_url)
    end
  end
end
